# LAB 1: Exploring Numpy

# Q1.

First, I install the numpy library

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

Now, I intialise an array by type casting a python list to an array

In [3]:
data1 = [0,98,67.5,34,23,12]
arr1 = np.array(data1)  # converts to ndarray
arr1

array([ 0. , 98. , 67.5, 34. , 23. , 12. ])

Following are some commonly used attributes of a numpy array namely 
- **dtype:**  specifies the homogenuous type of the array, default type being int32, float64 or object(for strings).
- **shape:** tells the size of various dimensions of the array, beginning from the innermost blocks of the array whose dimensions is specified by the very last element of the shape tuple and so on
- **ndim:** tells the dimensions of the array, which can also be seen by the number of square braces at the time of opening or closing the array.

In [4]:
arr1.dtype, arr1.shape, arr1.ndim

(dtype('float64'), (6,), 1)

Some other ways to initialise arrays

In [5]:
np.empty((4,3,2)) # I'm giving the dimensions here

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [6]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [7]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
np.arange(10, 30, 2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

The following creates an array of the same dimension as the given argument. There is also a zeros_like and empty_like equivalent.

In [9]:
np.ones_like(arr1) 

array([1., 1., 1., 1., 1., 1.])

The following creates an nxn identity matrix. ANother similar function is the identity method.

In [10]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

For typecasting, the following method is used:

In [11]:
arr1.astype('int32')

array([ 0, 98, 67, 34, 23, 12], dtype=int32)

## Vectorization
This numpy feature allows batch operations on data without applying nested for loops. It helps allow operations element-wise.

In [12]:
arr1*arr1 # multiplies element-wise

array([   0.  , 9604.  , 4556.25, 1156.  ,  529.  ,  144.  ])

In [13]:
arr1 ** 0.5 # value gets broadcast(propogated)

array([0.        , 9.89949494, 8.21583836, 5.83095189, 4.79583152,
       3.46410162])

## Basic Indexing and Slicing

# Q2.

In [14]:
data1 = [1,3,9,12,18]
data2 = [[1,5,2,0],[3,6,4,7]]
data3 = [['7','6'],['5','4'],['3','2']]
data4 = [[11,52,20,50],[34,61,43,17]]

In [15]:
arr1 = np.array(data1)
arr2 = np.array(data2)
arr3 = np.array(data3)
arr4 = np.array(data4)
print(arr1, arr2, arr3, arr4, sep='\n\n')

[ 1  3  9 12 18]

[[1 5 2 0]
 [3 6 4 7]]

[['7' '6']
 ['5' '4']
 ['3' '2']]

[[11 52 20 50]
 [34 61 43 17]]


# Q3.

In [16]:
arr1 += arr1
arr1


array([ 2,  6, 18, 24, 36])

In [17]:
arr1 *= 10
arr1

array([ 20,  60, 180, 240, 360])

In [18]:
arr1 = arr1.astype(np.int32)
arr2 = arr2.astype(np.int32)
arr3 = arr3.astype(np.int32)
arr4 = arr4.astype(np.int32)
print(arr1, arr2, arr3, arr4, sep='\n\n')

[ 20  60 180 240 360]

[[1 5 2 0]
 [3 6 4 7]]

[[7 6]
 [5 4]
 [3 2]]

[[11 52 20 50]
 [34 61 43 17]]


# Q4.

In [19]:
arr_zeros = np.zeros((3,5))
arr_ones = np.ones((2,8))
arr_rand = np.random.randint(100, size=(6,3))
print(arr_zeros, arr_ones, arr_rand, sep='\n\n')

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]

[[37 16  4]
 [77 81 68]
 [39 80 22]
 [41 17  5]
 [40 54 17]
 [70 61 21]]


# Q5.

In [20]:
arr1[2:4]**=2
arr1


array([   20,    60, 32400, 57600,   360], dtype=int32)

In [21]:
arr2[[0, 1],[1, 2]] **= 2
arr2

array([[ 1, 25,  2,  0],
       [ 3,  6, 16,  7]], dtype=int32)

# Q6.

In [22]:
subj = [['ML', 'OS', 'CCN'],['OS', 'AI', 'MP'], ['CCN', 'ML', 'AI']]
subj = np.array(subj)
subj

array([['ML', 'OS', 'CCN'],
       ['OS', 'AI', 'MP'],
       ['CCN', 'ML', 'AI']], dtype='<U3')

In [23]:
subj[(subj != 'ML') & (subj != 'AI')] = 0
subj

array([['ML', '0', '0'],
       ['0', 'AI', '0'],
       ['0', 'ML', 'AI']], dtype='<U3')

# Q7.

In [32]:
print(arr2.T, arr3.T, arr4.T, sep='\n\n')

[[ 1  3]
 [25  6]
 [ 2 16]
 [ 0  7]]

[[7 5 3]
 [6 4 2]]

[[11 34]
 [52 61]
 [20 43]
 [50 17]]


# Q8.

In [36]:
np.vstack((arr2, arr4))

array([[ 1, 25,  2,  0],
       [ 3,  6, 16,  7],
       [11, 52, 20, 50],
       [34, 61, 43, 17]], dtype=int32)

In [37]:
np.hstack((arr2, arr4))

array([[ 1, 25,  2,  0, 11, 52, 20, 50],
       [ 3,  6, 16,  7, 34, 61, 43, 17]], dtype=int32)

# Q9.

In [44]:
arr2 - arr2.mean(0)

array([[-1. ,  9.5, -7. , -3.5],
       [ 1. , -9.5,  7. ,  3.5]])

# Q10. 

In [45]:
arr2.reshape((4,2))

array([[ 1, 25],
       [ 2,  0],
       [ 3,  6],
       [16,  7]], dtype=int32)

# Q11.

In [49]:
marks = [[60,70,50],[40,60,80],[70,55,65]]
np.max(marks, 1)

array([70, 80, 70])

# Q12.