# Assignment 3: Regression

We intend to design a machine learning system for predicting humidity using temperature values as feature. <br>
The following table shows average temperature values and their corresponding average humidity values for 12 months of a
year for a certain city.

![table](images/table.png)

### a. Write linear regression equation for the prediction system.

### $$ y = \theta_1x + \theta_0  $$

### b. Find predicted values for humidity i.e. $$ h(x^{(i)}) $$if θ0 = 53.95 and θ1 = −0.56.

In [25]:
import numpy as np
from sklearn.linear_model import LinearRegression

In [7]:

temp = np.array([14.1, 16.7, 19.7, 25.2, 25.1, 18.8, 11.7, 10.2, 9.0, 9.1, 10.5, 12.6])
target = np.array([44.3, 50.4, 46.8, 33.7, 37.4, 54.2, 68.2, 69.0, 45.0, 51.3, 20.7, 24.4])

In [8]:
t0 = 53.95
t1 = -0.56

In [9]:
pred = t1*temp + t0
pred

array([46.054, 44.598, 42.918, 39.838, 39.894, 43.422, 47.398, 48.238,
       48.91 , 48.854, 48.07 , 46.894])

### c. Find the value of the cost function.

In [22]:
n = len(pred)
squared = (target-pred)**2
rss = sum(squared)
cost = 1/n * rss
cost

np.float64(196.00181733333335)

### d. Find R-squared value for this model.

In [24]:
mean = target.mean()
tss = sum((target-mean)**2)
r_squared = 1-rss/tss
r_squared

np.float64(0.04750608140669732)

In [35]:
# Verify from library
temp = temp.reshape((12,1)) # lr only takes 2D feature array
lr = LinearRegression().fit(temp, target)

In [36]:
lr.predict(temp)

array([46.07805259, 44.62655327, 42.95174638, 39.88126706, 39.93709396,
       43.45418845, 47.41789811, 48.25530156, 48.92522432, 48.86939742,
       48.08782087, 46.91545604])

In [38]:
lr.coef_, lr.intercept_

(array([-0.55826897]), np.float64(53.949645013249736))

### e. Propose two methods by which the R-squared value obtained in part c can be improved.