# Lab 11

## Q2.

In [19]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [8]:
from sklearn import datasets

iris = datasets.load_iris()
features = iris.data
target = iris.target

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [15]:
from sklearn.decomposition import KernelPCA

# Create support vector classifier
pca = KernelPCA(n_components=2, kernel="rbf", gamma=15)
# Train model
model = pca.fit_transform(features_standardized)

In [16]:
print("Original Features:", features_standardized.shape[1])
print("Reduced Features:", model.shape[1])

Original Features: 4
Reduced Features: 2


## Q3.

In [34]:
from sklearn.model_selection import train_test_split

trainX, testX, trainY, testY = train_test_split(model, target, random_state=2, test_size=0.2)

In [35]:
from sklearn.model_selection import train_test_split

trainX1, testX1, trainY1, testY1 = train_test_split(features, target, random_state=2, test_size=0.2)

## Support Vector Machine(Without PCA)

In [36]:
svc1 = SVC(kernel="rbf", C=100, gamma=10)
svc1.fit(trainX1, trainY1)

SVC(C=100, gamma=10)

In [38]:
predY_ = svc1.predict(testX1)

In [39]:
print("The accuracy is "+str(metrics.accuracy_score(testY1, predY_)*100)+"%")
cmatrix_=confusion_matrix(testY1, predY_)
print(cmatrix_)
metrics.precision_recall_fscore_support(testY1, predY_)

The accuracy is 93.33333333333333%
[[13  0  1]
 [ 0  7  1]
 [ 0  0  8]]


(array([1. , 1. , 0.8]),
 array([0.92857143, 0.875     , 1.        ]),
 array([0.96296296, 0.93333333, 0.88888889]),
 array([14,  8,  8]))

## Support Vector Machine

In [40]:
svc = SVC(kernel="rbf", C=100, gamma=10)
svc.fit(trainX, trainY)

SVC(C=100, gamma=10)

In [41]:
predY = svc.predict(testX)

In [42]:
print("The accuracy is "+str(metrics.accuracy_score(testY, predY)*100)+"%")
cmatrix=confusion_matrix(testY, predY)
print(cmatrix)
metrics.precision_recall_fscore_support(testY, predY)

The accuracy is 60.0%
[[8 1 5]
 [0 4 4]
 [0 2 6]]


(array([1.        , 0.57142857, 0.4       ]),
 array([0.57142857, 0.5       , 0.75      ]),
 array([0.72727273, 0.53333333, 0.52173913]),
 array([14,  8,  8]))

## Logistic Regression(Without PCA)

In [43]:
regr1 = LogisticRegression(random_state=2)
regr1.fit(trainX1, trainY1)

LogisticRegression(random_state=2)

In [44]:
predY1_ = regr1.predict(testX1)

In [45]:
print("The accuracy is "+str(metrics.accuracy_score(testY1, predY1_)*100)+"%")
cmatrix1_=confusion_matrix(testY1, predY1_)
print(cmatrix1_)
metrics.precision_recall_fscore_support(testY1, predY1_)

The accuracy is 96.66666666666667%
[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]


(array([1.        , 1.        , 0.88888889]),
 array([1.   , 0.875, 1.   ]),
 array([1.        , 0.93333333, 0.94117647]),
 array([14,  8,  8]))

## Logistic Regression

In [46]:
regr = LogisticRegression(random_state=2)
regr.fit(trainX, trainY)

LogisticRegression(random_state=2)

In [47]:
predY1 = regr.predict(testX)

In [48]:
print("The accuracy is "+str(metrics.accuracy_score(testY, predY1)*100)+"%")
cmatrix1=confusion_matrix(testY, predY1)
print(cmatrix1)
metrics.precision_recall_fscore_support(testY, predY1)

The accuracy is 53.333333333333336%
[[8 4 2]
 [0 8 0]
 [0 8 0]]


(array([1. , 0.4, 0. ]),
 array([0.57142857, 1.        , 0.        ]),
 array([0.72727273, 0.57142857, 0.        ]),
 array([14,  8,  8]))