# Lab 11

## Q2.

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression

from sklearn import metrics
from sklearn.metrics import confusion_matrix

In [29]:
from sklearn import datasets

iris = datasets.load_iris()
features = iris.data
target = iris.target

In [30]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
features_standardized = scaler.fit_transform(features)

In [31]:
from sklearn.decomposition import KernelPCA

# Create support vector classifier
pca = KernelPCA(n_components=2, kernel="rbf", gamma=15)
# Train model
model = pca.fit_transform(features_standardized)

In [32]:
print("Original Features:", features_standardized.shape[1])
print("Reduced Features:", model.shape[1])

Original Features: 4
Reduced Features: 2


## Q3.

In [33]:
from sklearn.model_selection import train_test_split

trainX1, testX1, trainY1, testY1 = train_test_split(features, target, random_state=2, test_size=0.2)

## Support Vector Machine(Without PCA)

In [34]:
svc1 = SVC(kernel="rbf", C=100, gamma=10)
svc1.fit(trainX1, trainY1)

SVC(C=100, gamma=10)

In [35]:
predY_ = svc1.predict(testX1)

In [36]:
print("The accuracy is "+str(metrics.accuracy_score(testY1, predY_)*100)+"%")
cmatrix_=confusion_matrix(testY1, predY_)
print(cmatrix_)
metrics.precision_recall_fscore_support(testY1, predY_)

The accuracy is 93.33333333333333%
[[13  0  1]
 [ 0  7  1]
 [ 0  0  8]]


(array([1. , 1. , 0.8]),
 array([0.92857143, 0.875     , 1.        ]),
 array([0.96296296, 0.93333333, 0.88888889]),
 array([14,  8,  8]))

## Support Vector Machine

In [37]:
svc = SVC(kernel="rbf", C=100, gamma=10)
svc.fit(trainX, trainY)

SVC(C=100, gamma=10)

In [38]:
predY = svc.predict(testX)

In [43]:
print("The accuracy is "+str(metrics.accuracy_score(testY, predY)*100)+"%")
cmatrix=confusion_matrix(testY, predY)
print(cmatrix)
metrics.precision_recall_fscore_support(testY, predY)

The accuracy is 8.807829181494661%
[[  0   0   0   0   0   0   0 114   0   0]
 [  0   0   0   0   0   0   0 115   0   0]
 [  0   0   0   0   0   0   0 110   0   0]
 [  0   0   0   0   0   0   0 115   0   0]
 [  0   0   0   0   0   0   0 128   0   0]
 [  0   0   0   0   0   0   0 102   0   0]
 [  0   0   0   0   0   0   0 109   0   0]
 [  0   0   0   0   0   0   0  99   0   0]
 [  0   0   0   0   0   0   0 112   0   0]
 [  0   0   0   0   0   0   0 120   0   0]]


(array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.08807829, 0.        , 0.        ]),
 array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]),
 array([0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.16189697, 0.        , 0.        ]),
 array([114, 115, 110, 115, 128, 102, 109,  99, 112, 120]))

## Logistic Regression(Without PCA)

In [44]:
regr1 = LogisticRegression(random_state=2)
regr1.fit(trainX1, trainY1)

LogisticRegression(random_state=2)

In [41]:
predY1_ = regr1.predict(testX1)

In [42]:
print("The accuracy is "+str(metrics.accuracy_score(testY1, predY1_)*100)+"%")
cmatrix1_=confusion_matrix(testY1, predY1_)
print(cmatrix1_)
metrics.precision_recall_fscore_support(testY1, predY1_)

The accuracy is 96.66666666666667%
[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]


(array([1.        , 1.        , 0.88888889]),
 array([1.   , 0.875, 1.   ]),
 array([1.        , 0.93333333, 0.94117647]),
 array([14,  8,  8]))

## Logistic Regression

In [ ]:
regr = LogisticRegression(random_state=2)
regr.fit(trainX, trainY)

LogisticRegression(random_state=2)

In [ ]:
predY1 = regr.predict(testX)

In [ ]:
print("The accuracy is "+str(metrics.accuracy_score(testY, predY1)*100)+"%")
cmatrix1=confusion_matrix(testY, predY1)
print(cmatrix1)
metrics.precision_recall_fscore_support(testY, predY1)

The accuracy is 53.333333333333336%
[[8 4 2]
 [0 8 0]
 [0 8 0]]


(array([1. , 0.4, 0. ]),
 array([0.57142857, 1.        , 0.        ]),
 array([0.72727273, 0.57142857, 0.        ]),
 array([14,  8,  8]))

## Q5.

In [45]:

import warnings
warnings.filterwarnings('ignore', category=UserWarning)

In [46]:
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

def solve(model, X, y, model_func):
  scaler = StandardScaler()
  features_standardized = scaler.fit_transform(X)

  pca09 = PCA(n_components=0.9)
  model09 = pca09.fit_transform(features_standardized)
  trainX, testX, trainY, testY = train_test_split(model09, y, random_state=2, test_size=0.2)
  lr=model_func(random_state=2)
  lr.fit(trainX, trainY)
  predY = lr.predict(testX)
  print(f"\n{model} with n_components = 0.9")
  print("Accuracy Score", accuracy_score(testY, predY))
  print("Precision Score", precision_score(testY, predY, average='micro'))
  print("Recall Score", recall_score(testY, predY, average='micro'))
  print("F1 Score", f1_score(testY, predY, average='micro'))

  pca095 = PCA(n_components=0.95)
  model095 = pca095.fit_transform(features_standardized)
  trainX, testX, trainY, testY = train_test_split(model095, y, random_state=2, test_size=0.2)
  lr=model_func(random_state=2)
  lr.fit(trainX, trainY)
  predY = lr.predict(testX)
  print(f"\n{model} with n_components = 0.95")
  print("Accuracy Score", accuracy_score(testY, predY))
  print("Precision Score", precision_score(testY, predY, average='micro'))
  print("Recall Score", recall_score(testY, predY, average='micro'))
  print("F1 Score", f1_score(testY, predY, average='micro'))

  pca099 = PCA(n_components=0.99)
  model099 = pca099.fit_transform(features_standardized)
  trainX, testX, trainY, testY = train_test_split(model099, y, random_state=2, test_size=0.2)
  lr=model_func(random_state=2)
  lr.fit(trainX, trainY)
  predY = lr.predict(testX)
  print(f"\n{model} with n_components = 0.99")
  print("Accuracy Score", accuracy_score(testY, predY))
  print("Precision Score", precision_score(testY, predY, average='micro'))
  print("Recall Score", recall_score(testY, predY, average='micro'))
  print("F1 Score", f1_score(testY, predY, average='micro'))

  pca10 = PCA(n_components=10)
  model10 = pca10.fit_transform(features_standardized)
  trainX, testX, trainY, testY = train_test_split(model10, y, random_state=2, test_size=0.2)
  lr=model_func(random_state=2)
  lr.fit(trainX, trainY)
  predY = lr.predict(testX)
  print(f"\n{model} with n_components = 10")
  print("Accuracy Score", accuracy_score(testY, predY))
  print("Precision Score", precision_score(testY, predY, average='micro'))
  print("Recall Score", recall_score(testY, predY, average='micro'))
  print("F1 Score", f1_score(testY, predY, average='micro'))

  if len(X.columns) > 30:

    pca30 = PCA(n_components=30)
    model30 = pca30.fit_transform(features_standardized)
    trainX, testX, trainY, testY = train_test_split(model30, y, random_state=2, test_size=0.2)
    lr=model_func(random_state=2)
    lr.fit(trainX, trainY)
    predY = lr.predict(testX)
    print(f"\n{model} with n_components = 30")
    print("Accuracy Score", accuracy_score(testY, predY))
    print("Precision Score", precision_score(testY, predY, average='micro'))
    print("Recall Score", recall_score(testY, predY, average='micro'))
    print("F1 Score", f1_score(testY, predY, average='micro'))

    pca40 = PCA(n_components=40)
    model40 = pca40.fit_transform(features_standardized)
    trainX, testX, trainY, testY = train_test_split(model40, y, random_state=2, test_size=0.2)
    lr=model_func(random_state=2)
    lr.fit(trainX, trainY)
    predY = lr.predict(testX)
    print(f"\n{model} with n_components = 40")
    print("Accuracy Score", accuracy_score(testY, predY))
    print("Precision Score", precision_score(testY, predY, average='micro'))
    print("Recall Score", recall_score(testY, predY, average='micro'))
    print("F1 Score", f1_score(testY, predY, average='micro'))

    pca50 = PCA(n_components=50)
    model50 = pca50.fit_transform(features_standardized)
    trainX, testX, trainY, testY = train_test_split(model50, y, random_state=2, test_size=0.2)
    lr=model_func(random_state=2)
    lr.fit(trainX, trainY)
    predY = lr.predict(testX)
    print(f"\n{model} with n_components = 50")
    print("Accuracy Score", accuracy_score(testY, predY))
    print("Precision Score", precision_score(testY, predY, average='micro'))
    print("Recall Score", recall_score(testY, predY, average='micro'))
    print("F1 Score", f1_score(testY, predY, average='micro'))


In [47]:
from ucimlrepo import fetch_ucirepo

optical_recognition_of_handwritten_digits = fetch_ucirepo(id=80)

X = optical_recognition_of_handwritten_digits.data.features
y = optical_recognition_of_handwritten_digits.data.targets

In [48]:
solve("Logistic Regression", X, y, LogisticRegression)


Logistic Regression with n_components = 0.9
Accuracy Score 0.9599644128113879
Precision Score 0.9599644128113879
Recall Score 0.9599644128113879
F1 Score 0.9599644128113879

Logistic Regression with n_components = 0.95
Accuracy Score 0.9608540925266904
Precision Score 0.9608540925266904
Recall Score 0.9608540925266904
F1 Score 0.9608540925266904

Logistic Regression with n_components = 0.99
Accuracy Score 0.9759786476868327
Precision Score 0.9759786476868327
Recall Score 0.9759786476868327
F1 Score 0.9759786476868327

Logistic Regression with n_components = 10
Accuracy Score 0.8923487544483986
Precision Score 0.8923487544483986
Recall Score 0.8923487544483986
F1 Score 0.8923487544483986

Logistic Regression with n_components = 30
Accuracy Score 0.9546263345195729
Precision Score 0.9546263345195729
Recall Score 0.9546263345195729
F1 Score 0.9546263345195729

Logistic Regression with n_components = 40
Accuracy Score 0.9599644128113879
Precision Score 0.9599644128113879
Recall Score 0.95

In [19]:
solve("SVM Classifier", X, y, SVC)


SVM Classifier with n_components = 0.9
Accuracy Score 0.9857651245551602
Precision Score 0.9857651245551602
Recall Score 0.9857651245551602
F1 Score 0.9857651245551602

SVM Classifier with n_components = 0.95
Accuracy Score 0.9884341637010676
Precision Score 0.9884341637010676
Recall Score 0.9884341637010676
F1 Score 0.9884341637010676

SVM Classifier with n_components = 0.99
Accuracy Score 0.9902135231316725
Precision Score 0.9902135231316725
Recall Score 0.9902135231316725
F1 Score 0.9902135231316725

SVM Classifier with n_components = 10
Accuracy Score 0.9608540925266904
Precision Score 0.9608540925266904
Recall Score 0.9608540925266904
F1 Score 0.9608540925266904

SVM Classifier with n_components = 30
Accuracy Score 0.9866548042704626
Precision Score 0.9866548042704626
Recall Score 0.9866548042704626
F1 Score 0.9866548042704626

SVM Classifier with n_components = 40
Accuracy Score 0.9884341637010676
Precision Score 0.9884341637010676
Recall Score 0.9884341637010676
F1 Score 0.9884

In [20]:
solve("Random Forest Classifer", X, y, RandomForestClassifier)


Random Forest Classifer with n_components = 0.9
Accuracy Score 0.9688612099644128
Precision Score 0.9688612099644128
Recall Score 0.9688612099644128
F1 Score 0.9688612099644128

Random Forest Classifer with n_components = 0.95
Accuracy Score 0.9733096085409253
Precision Score 0.9733096085409253
Recall Score 0.9733096085409253
F1 Score 0.9733096085409253

Random Forest Classifer with n_components = 0.99
Accuracy Score 0.9706405693950177
Precision Score 0.9706405693950177
Recall Score 0.9706405693950177
F1 Score 0.9706405693950177

Random Forest Classifer with n_components = 10
Accuracy Score 0.9483985765124555
Precision Score 0.9483985765124555
Recall Score 0.9483985765124555
F1 Score 0.9483985765124555

Random Forest Classifer with n_components = 30
Accuracy Score 0.9724199288256228
Precision Score 0.9724199288256228
Recall Score 0.9724199288256228
F1 Score 0.9724199288256228

Random Forest Classifer with n_components = 40
Accuracy Score 0.9750889679715302
Precision Score 0.9750889679

In [21]:
wine = fetch_ucirepo(id=109)

wine_X = wine.data.features
wine_y = wine.data.targets

In [49]:
solve("Logistic Regression", wine_X, wine_y, LogisticRegression)


Logistic Regression with n_components = 0.9
Accuracy Score 0.9722222222222222
Precision Score 0.9722222222222222
Recall Score 0.9722222222222222
F1 Score 0.9722222222222222

Logistic Regression with n_components = 0.95
Accuracy Score 1.0
Precision Score 1.0
Recall Score 1.0
F1 Score 1.0

Logistic Regression with n_components = 0.99
Accuracy Score 1.0
Precision Score 1.0
Recall Score 1.0
F1 Score 1.0

Logistic Regression with n_components = 10
Accuracy Score 1.0
Precision Score 1.0
Recall Score 1.0
F1 Score 1.0


In [50]:
solve("SVM Classifier", wine_X, wine_y, SVC)


SVM Classifier with n_components = 0.9
Accuracy Score 0.9444444444444444
Precision Score 0.9444444444444444
Recall Score 0.9444444444444444
F1 Score 0.9444444444444444

SVM Classifier with n_components = 0.95
Accuracy Score 0.9444444444444444
Precision Score 0.9444444444444444
Recall Score 0.9444444444444444
F1 Score 0.9444444444444444

SVM Classifier with n_components = 0.99
Accuracy Score 0.9444444444444444
Precision Score 0.9444444444444444
Recall Score 0.9444444444444444
F1 Score 0.9444444444444444

SVM Classifier with n_components = 10
Accuracy Score 0.9444444444444444
Precision Score 0.9444444444444444
Recall Score 0.9444444444444444
F1 Score 0.9444444444444444


In [51]:
solve("Random Forest Classifer", wine_X, wine_y, RandomForestClassifier)


Random Forest Classifer with n_components = 0.9
Accuracy Score 0.9444444444444444
Precision Score 0.9444444444444444
Recall Score 0.9444444444444444
F1 Score 0.9444444444444444

Random Forest Classifer with n_components = 0.95
Accuracy Score 0.9722222222222222
Precision Score 0.9722222222222222
Recall Score 0.9722222222222222
F1 Score 0.9722222222222222

Random Forest Classifer with n_components = 0.99
Accuracy Score 1.0
Precision Score 1.0
Recall Score 1.0
F1 Score 1.0

Random Forest Classifer with n_components = 10
Accuracy Score 0.9722222222222222
Precision Score 0.9722222222222222
Recall Score 0.9722222222222222
F1 Score 0.9722222222222222
